### ISSUE TITLE
Config not found

### ISSUE THREAD

**Issue by acurrieclark** [octoper/statamic-html-minify#1]
### Description

I am seeing a 
```
TypeError
Argument 1 passed to voku\helper\HtmlMin::doOptimizeViaHtmlDomParser() must be of the type bool, null given, called in ./vendor/octoper/statamic-html-minify/src/HtmlMinifyMiddleware.php on line 19
```

It would appear that the config is not being loaded. Am I missing a step?

### Additional information

* Statamic version: 3.0.2
* PHP version: 7.4

**Comment by octoper** [comment]
You need to run `php artisan vendor:publish --provider="Octoper\HtmlMinify\HtmlMinifyServiceProvider"`
to import the config file

**Comment by acurrieclark** [comment]
Ah, thanks very much. Would it be worth adding that step to the documentation?

**Comment by octoper** [comment]
Yeah I will add it right away!
Thank you very much!
